### ISSUE TITLE
How to Use with Openresty Nginx

### ISSUE THREAD

**Issue by pankajv82** [saks/lua-resty-newrelic#1]
Hi, 
I have openresty/nginx installed in CentOS 7.0. How can I use this? Can you send me some instructions? I have newrelic license.

**Comment by saks** [comment]
@pankajv82, please refer to updated [readme file](https://github.com/saks/lua-resty-newrelic/blob/master/README.md) and let me know if you have more questions.

**Comment by pankajv82** [comment]
Thanks a lot for quick response @saks I will try today and will reach to you in case I face some problems.

**Comment by pankajv82** [comment]
I was able to add this in my server but I get below message when I start Nginx, I can see app in Newrelic but no data being collected.

2016/12/06 17:04:19 [error] 4628#0: *1 [lua] newrelic_agent.lua:16: enable(): Starting newrelic agent., context: init_worker_by_lua*
2016/12/06 17:04:19 [error] 4630#0: *2 [lua] newrelic_agent.lua:16: enable(): Starting newrelic agent., context: init_worker_by_lua*

**Comment by pankajv82** [comment]
I get below message under accounts/<AccountID>/high_security in Newrelic website

Some of your applications are running New Relic agents that do not honor high security mode. Upgrade your agents to protect their data.
3Scale-INT (sdk version 0.16.2.0)

**Comment by saks** [comment]
Hey @pankajv82!

> I get below message under accounts//high_security in Newrelic website

In the archive with newrelic sdk you can find pdf file with some instructions. 
First of all you can enable SSL by setting env var `NEWRELIC_ENABLE_SSL` to `1`.
Another thing that you can enable is `NEWRELIC_ENABLE_HIGH_SECURITY` set to `1`.

Nginx config should look like:
```nginx
env NEWRELIC_ENABLE_HIGH_SECURITY=1;
env NEWRELIC_ENABLE_SSL=1;
```
Please try this out.

> I was able to add this in my server but I get below message when I start Nginx, I can see app in Newrelic but no data being collected.

Could you share your lua code for tracking transactions?

**Comment by pankajv82** [comment]
Still no luck with above. I don't see any thing going on in nginx-nr-agent.log so looks like data is not being pushed correctly or I am missing something. I got code from your example (copy/paste) just to test. 

env NEWRELIC_APP_LICENSE_KEY=***************;
  env NEWRELIC_APP_NAME=3Scale-INT;
  env NEWRELIC_ENABLE_HIGH_SECURITY=1;
  env NEWRELIC_ENABLE_SSL=1;

------------------------------------------
 location ~* ^/articles/?(.*) {
    rewrite_by_lua_block {
                    require('resty.newrelic_agent').start_web_transaction()
                }
     content_by_lua_block {
                    local newrelic = require 'resty.newrelic'
                newrelic on;
                    local newrelic_agent = require 'resty.newrelic_agent'
                    local nr_transaction_id = ngx.ctx.nr_transaction_id
                    newrelic.record_metric('test_connect', 1)

        -- track remote call
                    local http = require 'resty.http'
                    local uri = 'http://google.com'
                    local httpc = http.new()
                    local external_segment_id = newrelic.begin_external_segment(nr_transaction_id,
                    newrelic.NEWRELIC_ROOT_SEGMENT, uri, 'google home page')

                    httpc:request_uri(uri, { foo = 'bar' })
                    newrelic.end_segment(nr_transaction_id, external_segment_id)
    }
          include location.conf;
     log_by_lua_block {
                    require('resty.newrelic_agent').finish_web_transaction()
                }
    }

**Comment by pankajv82** [comment]
I can see similar solution https://github.com/yars/nginx_newrelic_module but in this case we need to recompile nginx with new module (ngx_http_newrelic_module) which I want to avoid. 

Does your code also require ngx_http_newrelic_module to be added with nginx (recompile)?

**Comment by saks** [comment]
Hey @pankajv82!

I added an example using docker container [here](https://github.com/saks/lua-resty-newrelic/tree/master/examples). Please refer to the readme file to find out how to use, but roughly it's simple as:
```
NEWRELIC_APP_LICENSE_KEY=<license key> docker-compose run --rm server
```

I tested this example code, it works for me and I proved this in many different ways. 

Unfortunately I cannot make this SDK send any data when using `NEWRELIC_ENABLE_HIGH_SECURITY=1`. It uses SSL mode by default so it should be good enough security already.

Please let me know if it works for you.

**Comment by pankajv82** [comment]
Thanks, Let me try this today. I will let you know...

**Comment by rasekar2000** [comment]
Thanks @saks . Currently , We are getting this error in my MAC.

https://github.com/docker/docker/issues/27076

RajRajen:examples rajrajen$ NEWRELIC_APP_LICENSE_KEY=ABC docker-compose run --rm server
ERROR: Cannot start service server: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/a52d4f7de2f1bfc0a14b3bd944028c4f27637a51b44451f9b21cea39b074f12f/etc/nginx/nginx.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/a52d4f7de2f1bfc0a14b3bd944028c4f27637a51b44451f9b21cea39b074f12f" caused "not a directory"

We are investigating further.

Thanks and Regards,
Raj

**Comment by pankajv82** [comment]
@saks Just to let you know, Raj is working with me.

**Comment by rasekar2000** [comment]
COPY nginx.conf /etc/nginx/

COPY content_by_lua_example.lua /opt/openresty/nginx/

currently for the workaround , I am doing the above in Dockerfile .

Regards,
raj

**Comment by rasekar2000** [comment]
![image](https://cloud.githubusercontent.com/assets/3443965/21031826/6b440a3c-bd5a-11e6-80c9-07c2b4c15a6b.png)
Thanks. It worked. We could see the REDIS connection Error in the Error Analytics.

Regards,
Raj

**Comment by saks** [comment]
Glad to hear :)
